import { Theme } from "@/Theme";

export const skillCategories = [
  {
    category: "Robotics & Embodied AI",
    color: Theme.colors.purple[400],
    description: "Sim-to-real transfer, control systems, and physics-grounded robotics",
    elements: [
      { symbol: "Mj", name: "MuJoCo" },
      { symbol: "Pb", name: "PyBullet" },
      { symbol: "Ppo", name: "PPO/SAC" },
      { symbol: "Dqn", name: "DQN" },
      { symbol: "Pmd", name: "POMDP" },
      { symbol: "Rl", name: "Reinforcement Learning" },
      { symbol: "Il", name: "Imitation Learning" },
      { symbol: "S2r", name: "Sim-to-Real Transfer" },
      { symbol: "Dra", name: "Domain Randomization" },
      { symbol: "Urf", name: "URDF/MJCF" },
    ],
  },
  {
    category: "Computer Vision & 3D",
    color: Theme.colors.cyan[400],
    description: "Neural rendering, 3D reconstruction, and spatial AI",
    elements: [
      { symbol: "Nrf", name: "NeRFs" },
      { symbol: "Sfm", name: "SfM/MVS Pipelines" },
      { symbol: "Clm", name: "COLMAP" },
      { symbol: "Omv", name: "OpenMVG" },
      { symbol: "O3d", name: "Open3D" },
      { symbol: "Ibr", name: "Image-Based Rendering" },
      { symbol: "Ocv", name: "OpenCV" },
      { symbol: "T3d", name: "PyTorch3D" },
      { symbol: "Mgm", name: "Multi-View Geometry" },
      { symbol: "Ccl", name: "Camera Calibration" },
      { symbol: "Pos", name: "Pose Estimation" },
      { symbol: "Web", name: "WebGL/Three.js Viewers" },
    ],
  },
  {
    category: "ML & Deep Learning",
    color: Theme.colors.pink[400],
    description: "Model training, transformers, and neural architectures",
    elements: [
      { symbol: "Pt", name: "PyTorch" },
      { symbol: "Tf", name: "TensorFlow" },
      { symbol: "Np", name: "NumPy" },
      { symbol: "Pd", name: "pandas" },
      { symbol: "Skl", name: "scikit-learn" },
      { symbol: "Rnn", name: "RNNs/LSTMs" },
      { symbol: "Trf", name: "Transformers" },
      { symbol: "Cnn", name: "CNNs" },
      { symbol: "Ssl", name: "Self-Supervised Learning" },
      { symbol: "Ctr", name: "Contrastive Learning" },
    ],
  },
  {
    category: "BCI & Neuroscience",
    color: Theme.colors.indigo[400],
    description: "Neural signal processing and brain-computer interfaces",
    elements: [
      { symbol: "Eeg", name: "EEG Decoding" },
      { symbol: "Egn", name: "EEGNet" },
      { symbol: "Mco", name: "MuJoCo" },
      { symbol: "Pbl", name: "PyBullet" },
      { symbol: "Rts", name: "Real-Time Control Systems" },
      { symbol: "Rfr", name: "Reinforcement Learning" },
      { symbol: "Iml", name: "Imitation Learning" },
      { symbol: "Sfu", name: "Sensor Fusion" },
      { symbol: "Mtr", name: "Motor Control" },
      { symbol: "Pom", name: "POMDPs" },
      { symbol: "Drn", name: "Domain Randomization" },
    ],
  },
  {
    category: "Scientific Computing",
    color: Theme.colors.teal[400],
    description: "Protein modeling, manifolds, and computational biology",
    elements: [
      { symbol: "Uma", name: "UMAP" },
      { symbol: "Mfl", name: "Manifold Learning" },
      { symbol: "Rep", name: "Representation Analysis" },
      { symbol: "Af2", name: "AlphaFold2" },
      { symbol: "Sig", name: "Signal Processing" },
      { symbol: "Spk", name: "Spiking Neuron Models" },
    ],
  },
  {
    category: "Full-Stack Engineering",
    color: Theme.colors.yellow[400],
    description: "Web applications and production systems",
    elements: [
      { symbol: "Ts", name: "TypeScript" },
      { symbol: "Js", name: "JavaScript" },
      { symbol: "Re", name: "React" },
      { symbol: "Nx", name: "Next.js" },
      { symbol: "Rdx", name: "Redux Toolkit" },
      { symbol: "Zus", name: "Zustand" },
      { symbol: "Mui", name: "Material UI" },
      { symbol: "Tw", name: "Tailwind" },
      { symbol: "Nde", name: "Node.js" },
      { symbol: "Exp", name: "Express" },
      { symbol: "Gql", name: "GraphQL" },
    ],
  },
  {
    category: "Systems & Cloud",
    color: Theme.colors.orange[400],
    description: "Infrastructure, DevOps, and data pipelines",
    elements: [
      { symbol: "Aws", name: "AWS" },
      { symbol: "Fst", name: "FastAPI" },
      { symbol: "Lnx", name: "Linux" },
      { symbol: "Git", name: "Git" },
      { symbol: "Rds", name: "Redis" },
      { symbol: "Mdb", name: "MongoDB" },
      { symbol: "Sql", name: "SQL" },
      { symbol: "Dpl", name: "Data Pipelines" },
    ],
  },
  {
    category: "Product Engineering",
    color: Theme.colors.lime[400],
    description: "Growth, analytics, and experimentation",
    elements: [
      { symbol: "Abt", name: "A/B Testing" },
      { symbol: "Gan", name: "Google Analytics" },
      { symbol: "Pos", name: "Posthog" },
      { symbol: "Cla", name: "MS Clarity" },
      { symbol: "Lth", name: "Lighthouse" },
      { symbol: "Seo", name: "SEO Optimization" },
      { symbol: "Okr", name: "OKRs" },
      { symbol: "Prd", name: "PRD/PRFAQ" },
      { symbol: "Uxr", name: "User Research" },
    ],
  },
];
